### ISSUE TITLE
Nieprzesyłanie skrótu hasła przy edycji użytkownika

### ISSUE THREAD

**Issue by Norbitor** [Norbitor/timesheet-net#2]
Podczas edycji użytkownika do przeglądarki przesyłany jest skrót hasła. Należy zmodyfikować tą funkcjonalność tak, aby skrót hasła nie był przesyłany do użytkownika

**Comment by gradzka** [comment]
Wysyłanie niepotrzebnych danych przy edycji użytkownika poprawione.
